package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'PetClinic'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, Project({
    id("PetClinic")
    name = "PetClinic"

    features {
        feature {
            id = "PROJECT_EXT_5"
            type = "project-graphs"
            param("series", """
                [
                  {
                    "type": "valueType",
                    "title": "Success Rate",
                    "sourceBuildTypeId": "PetClinic_ReleaseTrain_DeployPreProd",
                    "key": "SuccessRate"
                  }
                ]
            """.trimIndent())
            param("format", "text")
            param("title", "New chart title")
            param("seriesTitle", "Serie")
        }
    }
}))

