package patches.templates

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with id = 'MavenBuild'
accordingly, and delete the patch script.
*/
changeTemplate(RelativeId("MavenBuild")) {
    params {
        add {
            param("Environment", "")
        }
    }
}
